# Generated by Django 3.1.6 on 2021-02-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinzapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='number_of_refferral',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='refferal_bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='total_balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
