# Generated by Django 3.1.6 on 2021-02-14 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coinzapp', '0004_auto_20210214_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BasicPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PremiumPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='detail',
            name='total_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PremiumOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(blank=True, max_length=50)),
                ('select_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinzapp.premiumprice')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BasicOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(blank=True, max_length=50)),
                ('select_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinzapp.basicprice')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdvancedOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(blank=True, max_length=50)),
                ('select_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinzapp.advancedprice')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
