# Generated by Django 3.0.6 on 2021-02-15 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coinzapp', '0005_auto_20210214_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='current_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coinzapp.Package'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coinzapp.Status'),
        ),
    ]
