# Generated by Django 3.1.6 on 2021-02-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinzapp', '0006_auto_20210215_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='detail',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='detail',
            name='referral_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
