# Generated by Django 3.1.6 on 2021-02-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinzapp', '0008_auto_20210215_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedoption',
            name='coupon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='basicoption',
            name='coupon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='premiumoption',
            name='coupon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
