# Generated by Django 3.1.6 on 2021-02-15 14:05

import coinzapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinzapp', '0009_auto_20210215_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='vendor_id',
            field=models.CharField(blank=True, default=coinzapp.models.f, max_length=50, unique=True),
        ),
    ]
